[[Reactant]]
arch = "aarch64"
cuda_version = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30e8668c70f454e6df8cdfd5baf7ff3e1ee14aab"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "325f0c1375cdb78c69384f6e311ea087f110bb95d49d6c5925ac3d4123598ac2"
    url = "https://github.com/giordano/Reactant_jll.jl/releases/download/Reactant-v0.0.61+0/Reactant.v0.0.61.aarch64-linux-gnu-cxx11-cuda_version+12.4-gpu+cuda-mode+opt.tar.gz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a25cc3146b89516180e67e849a179378daf042bf"
gpu = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "e220b215cfa447b9bfafa1725252187c284dc5f6be8614b6567135055966b27f"
    url = "https://github.com/giordano/Reactant_jll.jl/releases/download/Reactant-v0.0.66+1/Reactant.v0.0.66.aarch64-linux-gnu-cxx11-cuda_version+none-gpu+none-mode+dbg.tar.gz"
